name: Workflow on Pull Requests
on:
  pull_request:
    branches: ["develop"]
jobs:
  teste:
    runs-on: ubuntu-latest
    steps:
      - name: Action de teste
        run: | 
          echo "Executando em pull request para a develop"
      - name: Alteração no card
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "Adicionando um comentário aqui sobre o PR"
            })