name: Workflow on Push
on:
  push:
    # branches: ["main","develop", "feature/*"]
    tags:
      - v*    
jobs:
  teste:
    runs-on: ubuntu-latest
    steps:
      - name: Action de teste
        run: | 
          echo "Executado apenas em main e feature"