name: Workflow on Push
on:
  push:
    branches: ["develop", "feature/*"]
    # branches-ignore: ["main"]
    paths: 
      - "src/**"  
    paths-ignore:
      - "workflow-execution-controll"    
      - "./readme.md"
    tags:
      - v*    
jobs:
  teste:
    runs-on: ubuntu-latest
    steps:
      - name: Action de teste
        run: | 
          echo "Executado apenas em main e feature"