name: Workflow Event
on:
  workflow_dispatch:
    inputs:
      exemplo-input:
        type: string
        description: "Teste de input"
        required: true
jobs:
  teste:
    runs-on: ubuntu-latest
    steps:
      - name: Action de teste
        run: | 
          echo "Disparou o evento com input: ${{ inputs.exemplo-input }}"